# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [39]:
import numpy as np
import pandas as pd

insurance_data = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv')

insurance_data.reset_index(drop=True, inplace=True)
insurance_data.columns = [c.lower().strip() for c in insurance_data.columns.values.tolist()]

# Assuming insurance_data is defined and contains the 'st' column
insurance_data.rename(columns={'st': 'state'}, inplace=True)

unique_states = insurance_data['state'].unique()

unique_states = insurance_data['state'].replace('WA', 'Washington', inplace=True)
unique_states = insurance_data['state'].replace('AZ', 'Arizona', inplace=True)
unique_states = insurance_data['state'].replace('Cali', 'California', inplace=True)

unique_states = insurance_data['gender'].unique()

unique_states = insurance_data['gender'].replace('Femal', 'F', inplace=True)
unique_states = insurance_data['gender'].replace('female', 'F', inplace=True)
unique_states = insurance_data['gender'].replace('Male', 'M', inplace=True)

unique_states = insurance_data['education'].unique()

unique_states = insurance_data['education'].replace('Bachelors', 'Bachelor', inplace=True)

unique_states = insurance_data['customer lifetime value'].unique()

insurance_data['customer lifetime value'] = insurance_data['customer lifetime value'].str.replace('%', '').astype(float)

unique_states = insurance_data['vehicle class'].unique()

unique_states = insurance_data['vehicle class'].replace('Sports Car', 'Luxury', inplace=True)
unique_states = insurance_data['vehicle class'].replace('Sports Car', 'Luxury', inplace=True)
unique_states = insurance_data['vehicle class'].replace('Luxury Car', 'Luxury', inplace=True)

unique_states = insurance_data['customer lifetime value'].unique()

unique_states = insurance_data['income'].unique()

unique_states = insurance_data['number of open complaints'].unique()

unique_states = insurance_data['number of open complaints'].replace('1/0/00', '0', inplace=True)
unique_states = insurance_data['number of open complaints'].replace('1/2/00', '2', inplace=True)
unique_states = insurance_data['number of open complaints'].replace('1/1/00', '1', inplace=True)
unique_states = insurance_data['number of open complaints'].replace('1/3/00', '3', inplace=True)
unique_states = insurance_data['number of open complaints'].replace('1/5/00', '5', inplace=True)
unique_states = insurance_data['number of open complaints'].replace('1/4/00', '4', inplace=True)

insurance_data.dropna(inplace=True)
print(insurance_data.shape)

# Convert all numeric columns to int
insurance_data.select_dtypes(include=['float64', 'int64']).astype(int)

# Keep changes in DataFrame
insurance_data[insurance_data.select_dtypes(include=['float64']).columns] = insurance_data.select_dtypes(include=['float64']).astype(int)

print(insurance_data.dtypes)

# Check for duplicate rows
duplicates = insurance_data.duplicated()

# Display the boolean Series
print(duplicates)

# Optionally, you can filter and show the duplicate rows
duplicate_rows = insurance_data[duplicates]
print(duplicate_rows)

# If you want to drop duplicates:
insurance_data.drop_duplicates(inplace=True)

# Reset the index
insurance_data.reset_index(drop=True, inplace=True)

# Display the updated DataFrame
print(insurance_data)

insurance_data.head()

(952, 11)
customer                     object
state                        object
gender                       object
education                    object
customer lifetime value       int32
income                        int32
monthly premium auto          int32
number of open complaints    object
policy type                  object
vehicle class                object
total claim amount            int32
dtype: object
1       False
2       False
3       False
4       False
5       False
        ...
1066    False
1067    False
1068    False
1069    False
1070    False
Length: 952, dtype: bool
Empty DataFrame
Columns: [customer, state, gender, education, customer lifetime value, income, monthly premium auto, number of open complaints, policy type, vehicle class, total claim amount]
Index: []
    customer       state gender             education  \
0    QZ44356     Arizona      F              Bachelor
1    AI49188      Nevada      F              Bachelor
2    WW63253  California      M              Bachelor
3    GA49547  Washington      M  High School or Below
4    OC83172      Oregon      F              Bachelor
..       ...         ...    ...                   ...
947  TM65736      Oregon      M                Master
948  VJ51327  California      F  High School or Below
949  GS98873     Arizona      F              Bachelor
950  CW49887  California      F                Master
951  MY31220  California      F               College

     customer lifetime value  income  monthly premium auto  \
0                     697953       0                    94
1                    1288743   48767                   108
2                     764586       0                   106
3                     536307   36357                    68
4                     825629   62902                    69
..                       ...     ...                   ...
947                   305955   38644                    78
948                  2031499   63209                   102
949                   323912   16061                    88
950                   462680   79487                   114
951                   899704   54230                   112

    number of open complaints     policy type  vehicle class  \
0                           0   Personal Auto  Four-Door Car
1                           0   Personal Auto   Two-Door Car
2                           0  Corporate Auto            SUV
3                           0   Personal Auto  Four-Door Car
4                           0   Personal Auto   Two-Door Car
..                        ...             ...            ...
947                         1   Personal Auto  Four-Door Car
948                         2   Personal Auto            SUV
949                         0   Personal Auto  Four-Door Car
950                         0    Special Auto            SUV
951                         0   Personal Auto   Two-Door Car

     total claim amount
0                  1131
1                   566
2                   529
3                    17
4                   159
..                  ...
947                 361
948                 207
949                 633
950                 547
951                 537

[952 rows x 11 columns]

C:\Users\Cecilia\AppData\Local\Temp\ipykernel_16264\1977500713.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unique_states = insurance_data['state'].replace('WA', 'Washington', inplace=True)
C:\Users\Cecilia\AppData\Local\Temp\ipykernel_16264\1977500713.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unique_states = insurance_data['state'].replace('AZ', 'Arizona', inplace=True)
C:\Users\Cecilia\AppData\Local\Temp\ipykernel_16264\1977500713.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unique_states = insurance_data['state'].replace('Cali', 'California', inplace=True)
C:\Users\Cecilia\AppData\Local\Temp\ipykernel_16264\1977500713.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unique_states = insurance_data['gender'].replace('Femal', 'F', inplace=True)
C:\Users\Cecilia\AppData\Local\Temp\ipykernel_16264\1977500713.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unique_states = insurance_data['gender'].replace('female', 'F', inplace=True)
C:\Users\Cecilia\AppData\Local\Temp\ipykernel_16264\1977500713.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unique_states = insurance_data['gender'].replace('Male', 'M', inplace=True)
C:\Users\Cecilia\AppData\Local\Temp\ipykernel_16264\1977500713.py:26: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unique_states = insurance_data['education'].replace('Bachelors', 'Bachelor', inplace=True)
C:\Users\Cecilia\AppData\Local\Temp\ipykernel_16264\1977500713.py:34: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unique_states = insurance_data['vehicle class'].replace('Sports Car', 'Luxury', inplace=True)
C:\Users\Cecilia\AppData\Local\Temp\ipykernel_16264\1977500713.py:35: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unique_states = insurance_data['vehicle class'].replace('Sports Car', 'Luxury', inplace=True)
C:\Users\Cecilia\AppData\Local\Temp\ipykernel_16264\1977500713.py:36: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unique_states = insurance_data['vehicle class'].replace('Luxury Car', 'Luxury', inplace=True)
C:\Users\Cecilia\AppData\Local\Temp\ipykernel_16264\1977500713.py:44: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unique_states = insurance_data['number of open complaints'].replace('1/0/00', '0', inplace=True)
C:\Users\Cecilia\AppData\Local\Temp\ipykernel_16264\1977500713.py:45: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unique_states = insurance_data['number of open complaints'].replace('1/2/00', '2', inplace=True)
C:\Users\Cecilia\AppData\Local\Temp\ipykernel_16264\1977500713.py:46: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unique_states = insurance_data['number of open complaints'].replace('1/1/00', '1', inplace=True)
C:\Users\Cecilia\AppData\Local\Temp\ipykernel_16264\1977500713.py:47: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unique_states = insurance_data['number of open complaints'].replace('1/3/00', '3', inplace=True)
C:\Users\Cecilia\AppData\Local\Temp\ipykernel_16264\1977500713.py:48: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unique_states = insurance_data['number of open complaints'].replace('1/5/00', '5', inplace=True)
C:\Users\Cecilia\AppData\Local\Temp\ipykernel_16264\1977500713.py:49: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unique_states = insurance_data['number of open complaints'].replace('1/4/00', '4', inplace=True)

,customer,state,gender,education,customer lifetime value,income,monthly premium auto,number of open complaints,policy type,vehicle class,total claim amount
0,QZ44356,Arizona,F,Bachelor,697953,0,94,0,Personal Auto,Four-Door Car,1131
1,AI49188,Nevada,F,Bachelor,1288743,48767,108,0,Personal Auto,Two-Door Car,566
2,WW63253,California,M,Bachelor,764586,0,106,0,Corporate Auto,SUV,529
3,GA49547,Washington,M,High School or Below,536307,36357,68,0,Personal Auto,Four-Door Car,17
4,OC83172,Oregon,F,Bachelor,825629,62902,69,0,Personal Auto,Two-Door Car,159

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [ ]:
# Your code goes here

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [ ]:
# Your code goes here